<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Seed email settings control data required for the notification system.
     */
    public function up(): void
    {
        $now = now();

        $emailSettings = [
            // Customer Emails
            [
                'email_type' => 'customer.email_verification',
                'name' => 'Email Verification',
                'description' => 'Sent when a user registers or changes their email address to verify ownership.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => true,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'customer.password_reset',
                'name' => 'Password Reset',
                'description' => 'Sent when a user requests to reset their password.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => true,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'customer.welcome',
                'name' => 'Welcome Email (Quick Checkout)',
                'description' => 'Sent to customers who create an account via quick checkout, includes password reset link.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'customer.order_confirmation',
                'name' => 'Order Confirmation',
                'description' => 'Sent immediately after an order is placed to confirm order details.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.payment_successful',
                'name' => 'Payment Successful',
                'description' => 'Sent when payment is successfully processed.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.payment_failed',
                'name' => 'Payment Failed',
                'description' => 'Sent when payment fails with instructions to retry.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.tan_payment_instructions',
                'name' => 'TAN Payment Instructions',
                'description' => 'Sent with TAN code, expiry time, and payment instructions for OneKhusa payments.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.order_processing',
                'name' => 'Order Processing',
                'description' => 'Sent when order status changes to processing.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'customer.order_shipped',
                'name' => 'Order Shipped',
                'description' => 'Sent when order is shipped with tracking information.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.order_delivered',
                'name' => 'Order Delivered',
                'description' => 'Sent when order is marked as delivered with review prompt.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.order_cancelled',
                'name' => 'Order Cancelled',
                'description' => 'Sent when an order is cancelled with reason and refund details.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'customer.refund_initiated',
                'name' => 'Refund Initiated',
                'description' => 'Sent when a refund is created with amount and timeline.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'customer.refund_completed',
                'name' => 'Refund Completed',
                'description' => 'Sent when refund is successfully processed.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'customer.contact_form_confirmation',
                'name' => 'Contact Form Confirmation',
                'description' => 'Sent to acknowledge receipt of contact form submission.',
                'category' => 'customer',
                'customer_enabled' => true,
                'seller_enabled' => false,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],

            // Seller Emails
            [
                'email_type' => 'seller.kyc_approved',
                'name' => 'KYC Approved',
                'description' => 'Sent when admin approves seller KYC verification.',
                'category' => 'seller',
                'customer_enabled' => false,
                'seller_enabled' => true,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'seller.kyc_rejected',
                'name' => 'KYC Rejected',
                'description' => 'Sent when admin rejects seller KYC with reason and resubmission instructions.',
                'category' => 'seller',
                'customer_enabled' => false,
                'seller_enabled' => true,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'seller.kyc_documents_requested',
                'name' => 'KYC Documents Requested',
                'description' => 'Sent when admin requests additional documents for KYC verification.',
                'category' => 'seller',
                'customer_enabled' => false,
                'seller_enabled' => true,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'seller.status_changed',
                'name' => 'Seller Status Changed',
                'description' => 'Sent when seller account status changes (suspended, active, etc).',
                'category' => 'seller',
                'customer_enabled' => false,
                'seller_enabled' => true,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'seller.new_order',
                'name' => 'New Order Received',
                'description' => 'Sent when a customer places an order containing seller items.',
                'category' => 'seller',
                'customer_enabled' => false,
                'seller_enabled' => true,
                'admin_enabled' => false,
                'sms_enabled' => true,
                'is_critical' => true,
            ],
            [
                'email_type' => 'seller.order_paid',
                'name' => 'Order Paid - Ready to Fulfill',
                'description' => 'Sent when payment is confirmed and items are ready for fulfillment.',
                'category' => 'seller',
                'customer_enabled' => false,
                'seller_enabled' => true,
                'admin_enabled' => false,
                'sms_enabled' => false,
                'is_critical' => false,
            ],

            // Admin Emails
            [
                'email_type' => 'admin.new_seller_registration',
                'name' => 'New Seller Registration',
                'description' => 'Alert when a new seller creates an account.',
                'category' => 'admin',
                'customer_enabled' => false,
                'seller_enabled' => false,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'admin.new_kyc_submission',
                'name' => 'New KYC Submission',
                'description' => 'Alert when a seller submits KYC documents for review.',
                'category' => 'admin',
                'customer_enabled' => false,
                'seller_enabled' => false,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'admin.new_contact_message',
                'name' => 'New Contact Message',
                'description' => 'Alert when a customer submits the contact form.',
                'category' => 'admin',
                'customer_enabled' => false,
                'seller_enabled' => false,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'admin.new_order',
                'name' => 'New Order Alert',
                'description' => 'Alert when an order is placed (optional threshold for high-value orders).',
                'category' => 'admin',
                'customer_enabled' => false,
                'seller_enabled' => false,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'admin.payment_failure',
                'name' => 'Payment Failure Alert',
                'description' => 'Alert when a payment fails.',
                'category' => 'admin',
                'customer_enabled' => false,
                'seller_enabled' => false,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
            [
                'email_type' => 'admin.refund',
                'name' => 'Refund Alert',
                'description' => 'Alert when a refund is initiated.',
                'category' => 'admin',
                'customer_enabled' => false,
                'seller_enabled' => false,
                'admin_enabled' => true,
                'sms_enabled' => false,
                'is_critical' => false,
            ],
        ];

        foreach ($emailSettings as $setting) {
            DB::table('email_settings')->updateOrInsert(
                ['email_type' => $setting['email_type']],
                array_merge($setting, ['created_at' => $now, 'updated_at' => $now])
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('email_settings')->delete();
    }
};
