<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG', 'code_2' => 'AF', 'phone_code' => '+93', 'currency_code' => 'AFN', 'is_active' => true],
            ['name' => 'Albania', 'code' => 'ALB', 'code_2' => 'AL', 'phone_code' => '+355', 'currency_code' => 'ALL', 'is_active' => true],
            ['name' => 'Algeria', 'code' => 'DZA', 'code_2' => 'DZ', 'phone_code' => '+213', 'currency_code' => 'DZD', 'is_active' => true],
            ['name' => 'Andorra', 'code' => 'AND', 'code_2' => 'AD', 'phone_code' => '+376', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Angola', 'code' => 'AGO', 'code_2' => 'AO', 'phone_code' => '+244', 'currency_code' => 'AOA', 'is_active' => true],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG', 'code_2' => 'AG', 'phone_code' => '+1-268', 'currency_code' => 'XCD', 'is_active' => true],
            ['name' => 'Argentina', 'code' => 'ARG', 'code_2' => 'AR', 'phone_code' => '+54', 'currency_code' => 'ARS', 'is_active' => true],
            ['name' => 'Armenia', 'code' => 'ARM', 'code_2' => 'AM', 'phone_code' => '+374', 'currency_code' => 'AMD', 'is_active' => true],
            ['name' => 'Australia', 'code' => 'AUS', 'code_2' => 'AU', 'phone_code' => '+61', 'currency_code' => 'AUD', 'is_active' => true],
            ['name' => 'Austria', 'code' => 'AUT', 'code_2' => 'AT', 'phone_code' => '+43', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Azerbaijan', 'code' => 'AZE', 'code_2' => 'AZ', 'phone_code' => '+994', 'currency_code' => 'AZN', 'is_active' => true],
            ['name' => 'Bahamas', 'code' => 'BHS', 'code_2' => 'BS', 'phone_code' => '+1-242', 'currency_code' => 'BSD', 'is_active' => true],
            ['name' => 'Bahrain', 'code' => 'BHR', 'code_2' => 'BH', 'phone_code' => '+973', 'currency_code' => 'BHD', 'is_active' => true],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'code_2' => 'BD', 'phone_code' => '+880', 'currency_code' => 'BDT', 'is_active' => true],
            ['name' => 'Barbados', 'code' => 'BRB', 'code_2' => 'BB', 'phone_code' => '+1-246', 'currency_code' => 'BBD', 'is_active' => true],
            ['name' => 'Belarus', 'code' => 'BLR', 'code_2' => 'BY', 'phone_code' => '+375', 'currency_code' => 'BYN', 'is_active' => true],
            ['name' => 'Belgium', 'code' => 'BEL', 'code_2' => 'BE', 'phone_code' => '+32', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Belize', 'code' => 'BLZ', 'code_2' => 'BZ', 'phone_code' => '+501', 'currency_code' => 'BZD', 'is_active' => true],
            ['name' => 'Benin', 'code' => 'BEN', 'code_2' => 'BJ', 'phone_code' => '+229', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Bhutan', 'code' => 'BTN', 'code_2' => 'BT', 'phone_code' => '+975', 'currency_code' => 'BTN', 'is_active' => true],
            ['name' => 'Bolivia', 'code' => 'BOL', 'code_2' => 'BO', 'phone_code' => '+591', 'currency_code' => 'BOB', 'is_active' => true],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'code_2' => 'BA', 'phone_code' => '+387', 'currency_code' => 'BAM', 'is_active' => true],
            ['name' => 'Botswana', 'code' => 'BWA', 'code_2' => 'BW', 'phone_code' => '+267', 'currency_code' => 'BWP', 'is_active' => true],
            ['name' => 'Brazil', 'code' => 'BRA', 'code_2' => 'BR', 'phone_code' => '+55', 'currency_code' => 'BRL', 'is_active' => true],
            ['name' => 'Brunei', 'code' => 'BRN', 'code_2' => 'BN', 'phone_code' => '+673', 'currency_code' => 'BND', 'is_active' => true],
            ['name' => 'Bulgaria', 'code' => 'BGR', 'code_2' => 'BG', 'phone_code' => '+359', 'currency_code' => 'BGN', 'is_active' => true],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'code_2' => 'BF', 'phone_code' => '+226', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Burundi', 'code' => 'BDI', 'code_2' => 'BI', 'phone_code' => '+257', 'currency_code' => 'BIF', 'is_active' => true],
            ['name' => 'Cambodia', 'code' => 'KHM', 'code_2' => 'KH', 'phone_code' => '+855', 'currency_code' => 'KHR', 'is_active' => true],
            ['name' => 'Cameroon', 'code' => 'CMR', 'code_2' => 'CM', 'phone_code' => '+237', 'currency_code' => 'XAF', 'is_active' => true],
            ['name' => 'Canada', 'code' => 'CAN', 'code_2' => 'CA', 'phone_code' => '+1', 'currency_code' => 'CAD', 'is_active' => true],
            ['name' => 'Cape Verde', 'code' => 'CPV', 'code_2' => 'CV', 'phone_code' => '+238', 'currency_code' => 'CVE', 'is_active' => true],
            ['name' => 'Central African Republic', 'code' => 'CAF', 'code_2' => 'CF', 'phone_code' => '+236', 'currency_code' => 'XAF', 'is_active' => true],
            ['name' => 'Chad', 'code' => 'TCD', 'code_2' => 'TD', 'phone_code' => '+235', 'currency_code' => 'XAF', 'is_active' => true],
            ['name' => 'Chile', 'code' => 'CHL', 'code_2' => 'CL', 'phone_code' => '+56', 'currency_code' => 'CLP', 'is_active' => true],
            ['name' => 'China', 'code' => 'CHN', 'code_2' => 'CN', 'phone_code' => '+86', 'currency_code' => 'CNY', 'is_active' => true],
            ['name' => 'Colombia', 'code' => 'COL', 'code_2' => 'CO', 'phone_code' => '+57', 'currency_code' => 'COP', 'is_active' => true],
            ['name' => 'Comoros', 'code' => 'COM', 'code_2' => 'KM', 'phone_code' => '+269', 'currency_code' => 'KMF', 'is_active' => true],
            ['name' => 'Congo', 'code' => 'COG', 'code_2' => 'CG', 'phone_code' => '+242', 'currency_code' => 'XAF', 'is_active' => true],
            ['name' => 'Congo (Democratic Republic)', 'code' => 'COD', 'code_2' => 'CD', 'phone_code' => '+243', 'currency_code' => 'CDF', 'is_active' => true],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'code_2' => 'CR', 'phone_code' => '+506', 'currency_code' => 'CRC', 'is_active' => true],
            ['name' => 'Croatia', 'code' => 'HRV', 'code_2' => 'HR', 'phone_code' => '+385', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Cuba', 'code' => 'CUB', 'code_2' => 'CU', 'phone_code' => '+53', 'currency_code' => 'CUP', 'is_active' => true],
            ['name' => 'Cyprus', 'code' => 'CYP', 'code_2' => 'CY', 'phone_code' => '+357', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Czech Republic', 'code' => 'CZE', 'code_2' => 'CZ', 'phone_code' => '+420', 'currency_code' => 'CZK', 'is_active' => true],
            ['name' => 'Denmark', 'code' => 'DNK', 'code_2' => 'DK', 'phone_code' => '+45', 'currency_code' => 'DKK', 'is_active' => true],
            ['name' => 'Djibouti', 'code' => 'DJI', 'code_2' => 'DJ', 'phone_code' => '+253', 'currency_code' => 'DJF', 'is_active' => true],
            ['name' => 'Dominica', 'code' => 'DMA', 'code_2' => 'DM', 'phone_code' => '+1-767', 'currency_code' => 'XCD', 'is_active' => true],
            ['name' => 'Dominican Republic', 'code' => 'DOM', 'code_2' => 'DO', 'phone_code' => '+1-809', 'currency_code' => 'DOP', 'is_active' => true],
            ['name' => 'Ecuador', 'code' => 'ECU', 'code_2' => 'EC', 'phone_code' => '+593', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Egypt', 'code' => 'EGY', 'code_2' => 'EG', 'phone_code' => '+20', 'currency_code' => 'EGP', 'is_active' => true],
            ['name' => 'El Salvador', 'code' => 'SLV', 'code_2' => 'SV', 'phone_code' => '+503', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'code_2' => 'GQ', 'phone_code' => '+240', 'currency_code' => 'XAF', 'is_active' => true],
            ['name' => 'Eritrea', 'code' => 'ERI', 'code_2' => 'ER', 'phone_code' => '+291', 'currency_code' => 'ERN', 'is_active' => true],
            ['name' => 'Estonia', 'code' => 'EST', 'code_2' => 'EE', 'phone_code' => '+372', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Eswatini', 'code' => 'SWZ', 'code_2' => 'SZ', 'phone_code' => '+268', 'currency_code' => 'SZL', 'is_active' => true],
            ['name' => 'Ethiopia', 'code' => 'ETH', 'code_2' => 'ET', 'phone_code' => '+251', 'currency_code' => 'ETB', 'is_active' => true],
            ['name' => 'Fiji', 'code' => 'FJI', 'code_2' => 'FJ', 'phone_code' => '+679', 'currency_code' => 'FJD', 'is_active' => true],
            ['name' => 'Finland', 'code' => 'FIN', 'code_2' => 'FI', 'phone_code' => '+358', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'France', 'code' => 'FRA', 'code_2' => 'FR', 'phone_code' => '+33', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Gabon', 'code' => 'GAB', 'code_2' => 'GA', 'phone_code' => '+241', 'currency_code' => 'XAF', 'is_active' => true],
            ['name' => 'Gambia', 'code' => 'GMB', 'code_2' => 'GM', 'phone_code' => '+220', 'currency_code' => 'GMD', 'is_active' => true],
            ['name' => 'Georgia', 'code' => 'GEO', 'code_2' => 'GE', 'phone_code' => '+995', 'currency_code' => 'GEL', 'is_active' => true],
            ['name' => 'Germany', 'code' => 'DEU', 'code_2' => 'DE', 'phone_code' => '+49', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Ghana', 'code' => 'GHA', 'code_2' => 'GH', 'phone_code' => '+233', 'currency_code' => 'GHS', 'is_active' => true],
            ['name' => 'Greece', 'code' => 'GRC', 'code_2' => 'GR', 'phone_code' => '+30', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Grenada', 'code' => 'GRD', 'code_2' => 'GD', 'phone_code' => '+1-473', 'currency_code' => 'XCD', 'is_active' => true],
            ['name' => 'Guatemala', 'code' => 'GTM', 'code_2' => 'GT', 'phone_code' => '+502', 'currency_code' => 'GTQ', 'is_active' => true],
            ['name' => 'Guinea', 'code' => 'GIN', 'code_2' => 'GN', 'phone_code' => '+224', 'currency_code' => 'GNF', 'is_active' => true],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'code_2' => 'GW', 'phone_code' => '+245', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Guyana', 'code' => 'GUY', 'code_2' => 'GY', 'phone_code' => '+592', 'currency_code' => 'GYD', 'is_active' => true],
            ['name' => 'Haiti', 'code' => 'HTI', 'code_2' => 'HT', 'phone_code' => '+509', 'currency_code' => 'HTG', 'is_active' => true],
            ['name' => 'Honduras', 'code' => 'HND', 'code_2' => 'HN', 'phone_code' => '+504', 'currency_code' => 'HNL', 'is_active' => true],
            ['name' => 'Hungary', 'code' => 'HUN', 'code_2' => 'HU', 'phone_code' => '+36', 'currency_code' => 'HUF', 'is_active' => true],
            ['name' => 'Iceland', 'code' => 'ISL', 'code_2' => 'IS', 'phone_code' => '+354', 'currency_code' => 'ISK', 'is_active' => true],
            ['name' => 'India', 'code' => 'IND', 'code_2' => 'IN', 'phone_code' => '+91', 'currency_code' => 'INR', 'is_active' => true],
            ['name' => 'Indonesia', 'code' => 'IDN', 'code_2' => 'ID', 'phone_code' => '+62', 'currency_code' => 'IDR', 'is_active' => true],
            ['name' => 'Iran', 'code' => 'IRN', 'code_2' => 'IR', 'phone_code' => '+98', 'currency_code' => 'IRR', 'is_active' => true],
            ['name' => 'Iraq', 'code' => 'IRQ', 'code_2' => 'IQ', 'phone_code' => '+964', 'currency_code' => 'IQD', 'is_active' => true],
            ['name' => 'Ireland', 'code' => 'IRL', 'code_2' => 'IE', 'phone_code' => '+353', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Israel', 'code' => 'ISR', 'code_2' => 'IL', 'phone_code' => '+972', 'currency_code' => 'ILS', 'is_active' => true],
            ['name' => 'Italy', 'code' => 'ITA', 'code_2' => 'IT', 'phone_code' => '+39', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Ivory Coast', 'code' => 'CIV', 'code_2' => 'CI', 'phone_code' => '+225', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Jamaica', 'code' => 'JAM', 'code_2' => 'JM', 'phone_code' => '+1-876', 'currency_code' => 'JMD', 'is_active' => true],
            ['name' => 'Japan', 'code' => 'JPN', 'code_2' => 'JP', 'phone_code' => '+81', 'currency_code' => 'JPY', 'is_active' => true],
            ['name' => 'Jordan', 'code' => 'JOR', 'code_2' => 'JO', 'phone_code' => '+962', 'currency_code' => 'JOD', 'is_active' => true],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'code_2' => 'KZ', 'phone_code' => '+7', 'currency_code' => 'KZT', 'is_active' => true],
            ['name' => 'Kenya', 'code' => 'KEN', 'code_2' => 'KE', 'phone_code' => '+254', 'currency_code' => 'KES', 'is_active' => true],
            ['name' => 'Kiribati', 'code' => 'KIR', 'code_2' => 'KI', 'phone_code' => '+686', 'currency_code' => 'AUD', 'is_active' => true],
            ['name' => 'Kuwait', 'code' => 'KWT', 'code_2' => 'KW', 'phone_code' => '+965', 'currency_code' => 'KWD', 'is_active' => true],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'code_2' => 'KG', 'phone_code' => '+996', 'currency_code' => 'KGS', 'is_active' => true],
            ['name' => 'Laos', 'code' => 'LAO', 'code_2' => 'LA', 'phone_code' => '+856', 'currency_code' => 'LAK', 'is_active' => true],
            ['name' => 'Latvia', 'code' => 'LVA', 'code_2' => 'LV', 'phone_code' => '+371', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Lebanon', 'code' => 'LBN', 'code_2' => 'LB', 'phone_code' => '+961', 'currency_code' => 'LBP', 'is_active' => true],
            ['name' => 'Lesotho', 'code' => 'LSO', 'code_2' => 'LS', 'phone_code' => '+266', 'currency_code' => 'LSL', 'is_active' => true],
            ['name' => 'Liberia', 'code' => 'LBR', 'code_2' => 'LR', 'phone_code' => '+231', 'currency_code' => 'LRD', 'is_active' => true],
            ['name' => 'Libya', 'code' => 'LBY', 'code_2' => 'LY', 'phone_code' => '+218', 'currency_code' => 'LYD', 'is_active' => true],
            ['name' => 'Liechtenstein', 'code' => 'LIE', 'code_2' => 'LI', 'phone_code' => '+423', 'currency_code' => 'CHF', 'is_active' => true],
            ['name' => 'Lithuania', 'code' => 'LTU', 'code_2' => 'LT', 'phone_code' => '+370', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'code_2' => 'LU', 'phone_code' => '+352', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Madagascar', 'code' => 'MDG', 'code_2' => 'MG', 'phone_code' => '+261', 'currency_code' => 'MGA', 'is_active' => true],
            ['name' => 'Malawi', 'code' => 'MWI', 'code_2' => 'MW', 'phone_code' => '+265', 'currency_code' => 'MWK', 'is_active' => true],
            ['name' => 'Malaysia', 'code' => 'MYS', 'code_2' => 'MY', 'phone_code' => '+60', 'currency_code' => 'MYR', 'is_active' => true],
            ['name' => 'Maldives', 'code' => 'MDV', 'code_2' => 'MV', 'phone_code' => '+960', 'currency_code' => 'MVR', 'is_active' => true],
            ['name' => 'Mali', 'code' => 'MLI', 'code_2' => 'ML', 'phone_code' => '+223', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Malta', 'code' => 'MLT', 'code_2' => 'MT', 'phone_code' => '+356', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Marshall Islands', 'code' => 'MHL', 'code_2' => 'MH', 'phone_code' => '+692', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Mauritania', 'code' => 'MRT', 'code_2' => 'MR', 'phone_code' => '+222', 'currency_code' => 'MRU', 'is_active' => true],
            ['name' => 'Mauritius', 'code' => 'MUS', 'code_2' => 'MU', 'phone_code' => '+230', 'currency_code' => 'MUR', 'is_active' => true],
            ['name' => 'Mexico', 'code' => 'MEX', 'code_2' => 'MX', 'phone_code' => '+52', 'currency_code' => 'MXN', 'is_active' => true],
            ['name' => 'Micronesia', 'code' => 'FSM', 'code_2' => 'FM', 'phone_code' => '+691', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Moldova', 'code' => 'MDA', 'code_2' => 'MD', 'phone_code' => '+373', 'currency_code' => 'MDL', 'is_active' => true],
            ['name' => 'Monaco', 'code' => 'MCO', 'code_2' => 'MC', 'phone_code' => '+377', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Mongolia', 'code' => 'MNG', 'code_2' => 'MN', 'phone_code' => '+976', 'currency_code' => 'MNT', 'is_active' => true],
            ['name' => 'Montenegro', 'code' => 'MNE', 'code_2' => 'ME', 'phone_code' => '+382', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Morocco', 'code' => 'MAR', 'code_2' => 'MA', 'phone_code' => '+212', 'currency_code' => 'MAD', 'is_active' => true],
            ['name' => 'Mozambique', 'code' => 'MOZ', 'code_2' => 'MZ', 'phone_code' => '+258', 'currency_code' => 'MZN', 'is_active' => true],
            ['name' => 'Myanmar', 'code' => 'MMR', 'code_2' => 'MM', 'phone_code' => '+95', 'currency_code' => 'MMK', 'is_active' => true],
            ['name' => 'Namibia', 'code' => 'NAM', 'code_2' => 'NA', 'phone_code' => '+264', 'currency_code' => 'NAD', 'is_active' => true],
            ['name' => 'Nauru', 'code' => 'NRU', 'code_2' => 'NR', 'phone_code' => '+674', 'currency_code' => 'AUD', 'is_active' => true],
            ['name' => 'Nepal', 'code' => 'NPL', 'code_2' => 'NP', 'phone_code' => '+977', 'currency_code' => 'NPR', 'is_active' => true],
            ['name' => 'Netherlands', 'code' => 'NLD', 'code_2' => 'NL', 'phone_code' => '+31', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'New Zealand', 'code' => 'NZL', 'code_2' => 'NZ', 'phone_code' => '+64', 'currency_code' => 'NZD', 'is_active' => true],
            ['name' => 'Nicaragua', 'code' => 'NIC', 'code_2' => 'NI', 'phone_code' => '+505', 'currency_code' => 'NIO', 'is_active' => true],
            ['name' => 'Niger', 'code' => 'NER', 'code_2' => 'NE', 'phone_code' => '+227', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Nigeria', 'code' => 'NGA', 'code_2' => 'NG', 'phone_code' => '+234', 'currency_code' => 'NGN', 'is_active' => true],
            ['name' => 'North Korea', 'code' => 'PRK', 'code_2' => 'KP', 'phone_code' => '+850', 'currency_code' => 'KPW', 'is_active' => true],
            ['name' => 'North Macedonia', 'code' => 'MKD', 'code_2' => 'MK', 'phone_code' => '+389', 'currency_code' => 'MKD', 'is_active' => true],
            ['name' => 'Norway', 'code' => 'NOR', 'code_2' => 'NO', 'phone_code' => '+47', 'currency_code' => 'NOK', 'is_active' => true],
            ['name' => 'Oman', 'code' => 'OMN', 'code_2' => 'OM', 'phone_code' => '+968', 'currency_code' => 'OMR', 'is_active' => true],
            ['name' => 'Pakistan', 'code' => 'PAK', 'code_2' => 'PK', 'phone_code' => '+92', 'currency_code' => 'PKR', 'is_active' => true],
            ['name' => 'Palau', 'code' => 'PLW', 'code_2' => 'PW', 'phone_code' => '+680', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Palestine', 'code' => 'PSE', 'code_2' => 'PS', 'phone_code' => '+970', 'currency_code' => 'ILS', 'is_active' => true],
            ['name' => 'Panama', 'code' => 'PAN', 'code_2' => 'PA', 'phone_code' => '+507', 'currency_code' => 'PAB', 'is_active' => true],
            ['name' => 'Papua New Guinea', 'code' => 'PNG', 'code_2' => 'PG', 'phone_code' => '+675', 'currency_code' => 'PGK', 'is_active' => true],
            ['name' => 'Paraguay', 'code' => 'PRY', 'code_2' => 'PY', 'phone_code' => '+595', 'currency_code' => 'PYG', 'is_active' => true],
            ['name' => 'Peru', 'code' => 'PER', 'code_2' => 'PE', 'phone_code' => '+51', 'currency_code' => 'PEN', 'is_active' => true],
            ['name' => 'Philippines', 'code' => 'PHL', 'code_2' => 'PH', 'phone_code' => '+63', 'currency_code' => 'PHP', 'is_active' => true],
            ['name' => 'Poland', 'code' => 'POL', 'code_2' => 'PL', 'phone_code' => '+48', 'currency_code' => 'PLN', 'is_active' => true],
            ['name' => 'Portugal', 'code' => 'PRT', 'code_2' => 'PT', 'phone_code' => '+351', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Qatar', 'code' => 'QAT', 'code_2' => 'QA', 'phone_code' => '+974', 'currency_code' => 'QAR', 'is_active' => true],
            ['name' => 'Romania', 'code' => 'ROU', 'code_2' => 'RO', 'phone_code' => '+40', 'currency_code' => 'RON', 'is_active' => true],
            ['name' => 'Russia', 'code' => 'RUS', 'code_2' => 'RU', 'phone_code' => '+7', 'currency_code' => 'RUB', 'is_active' => true],
            ['name' => 'Rwanda', 'code' => 'RWA', 'code_2' => 'RW', 'phone_code' => '+250', 'currency_code' => 'RWF', 'is_active' => true],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'code_2' => 'KN', 'phone_code' => '+1-869', 'currency_code' => 'XCD', 'is_active' => true],
            ['name' => 'Saint Lucia', 'code' => 'LCA', 'code_2' => 'LC', 'phone_code' => '+1-758', 'currency_code' => 'XCD', 'is_active' => true],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'code_2' => 'VC', 'phone_code' => '+1-784', 'currency_code' => 'XCD', 'is_active' => true],
            ['name' => 'Samoa', 'code' => 'WSM', 'code_2' => 'WS', 'phone_code' => '+685', 'currency_code' => 'WST', 'is_active' => true],
            ['name' => 'San Marino', 'code' => 'SMR', 'code_2' => 'SM', 'phone_code' => '+378', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP', 'code_2' => 'ST', 'phone_code' => '+239', 'currency_code' => 'STN', 'is_active' => true],
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'code_2' => 'SA', 'phone_code' => '+966', 'currency_code' => 'SAR', 'is_active' => true],
            ['name' => 'Senegal', 'code' => 'SEN', 'code_2' => 'SN', 'phone_code' => '+221', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Serbia', 'code' => 'SRB', 'code_2' => 'RS', 'phone_code' => '+381', 'currency_code' => 'RSD', 'is_active' => true],
            ['name' => 'Seychelles', 'code' => 'SYC', 'code_2' => 'SC', 'phone_code' => '+248', 'currency_code' => 'SCR', 'is_active' => true],
            ['name' => 'Sierra Leone', 'code' => 'SLE', 'code_2' => 'SL', 'phone_code' => '+232', 'currency_code' => 'SLL', 'is_active' => true],
            ['name' => 'Singapore', 'code' => 'SGP', 'code_2' => 'SG', 'phone_code' => '+65', 'currency_code' => 'SGD', 'is_active' => true],
            ['name' => 'Slovakia', 'code' => 'SVK', 'code_2' => 'SK', 'phone_code' => '+421', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Slovenia', 'code' => 'SVN', 'code_2' => 'SI', 'phone_code' => '+386', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Solomon Islands', 'code' => 'SLB', 'code_2' => 'SB', 'phone_code' => '+677', 'currency_code' => 'SBD', 'is_active' => true],
            ['name' => 'Somalia', 'code' => 'SOM', 'code_2' => 'SO', 'phone_code' => '+252', 'currency_code' => 'SOS', 'is_active' => true],
            ['name' => 'South Africa', 'code' => 'ZAF', 'code_2' => 'ZA', 'phone_code' => '+27', 'currency_code' => 'ZAR', 'is_active' => true],
            ['name' => 'South Korea', 'code' => 'KOR', 'code_2' => 'KR', 'phone_code' => '+82', 'currency_code' => 'KRW', 'is_active' => true],
            ['name' => 'South Sudan', 'code' => 'SSD', 'code_2' => 'SS', 'phone_code' => '+211', 'currency_code' => 'SSP', 'is_active' => true],
            ['name' => 'Spain', 'code' => 'ESP', 'code_2' => 'ES', 'phone_code' => '+34', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'code_2' => 'LK', 'phone_code' => '+94', 'currency_code' => 'LKR', 'is_active' => true],
            ['name' => 'Sudan', 'code' => 'SDN', 'code_2' => 'SD', 'phone_code' => '+249', 'currency_code' => 'SDG', 'is_active' => true],
            ['name' => 'Suriname', 'code' => 'SUR', 'code_2' => 'SR', 'phone_code' => '+597', 'currency_code' => 'SRD', 'is_active' => true],
            ['name' => 'Sweden', 'code' => 'SWE', 'code_2' => 'SE', 'phone_code' => '+46', 'currency_code' => 'SEK', 'is_active' => true],
            ['name' => 'Switzerland', 'code' => 'CHE', 'code_2' => 'CH', 'phone_code' => '+41', 'currency_code' => 'CHF', 'is_active' => true],
            ['name' => 'Syria', 'code' => 'SYR', 'code_2' => 'SY', 'phone_code' => '+963', 'currency_code' => 'SYP', 'is_active' => true],
            ['name' => 'Taiwan', 'code' => 'TWN', 'code_2' => 'TW', 'phone_code' => '+886', 'currency_code' => 'TWD', 'is_active' => true],
            ['name' => 'Tajikistan', 'code' => 'TJK', 'code_2' => 'TJ', 'phone_code' => '+992', 'currency_code' => 'TJS', 'is_active' => true],
            ['name' => 'Tanzania', 'code' => 'TZA', 'code_2' => 'TZ', 'phone_code' => '+255', 'currency_code' => 'TZS', 'is_active' => true],
            ['name' => 'Thailand', 'code' => 'THA', 'code_2' => 'TH', 'phone_code' => '+66', 'currency_code' => 'THB', 'is_active' => true],
            ['name' => 'Timor-Leste', 'code' => 'TLS', 'code_2' => 'TL', 'phone_code' => '+670', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Togo', 'code' => 'TGO', 'code_2' => 'TG', 'phone_code' => '+228', 'currency_code' => 'XOF', 'is_active' => true],
            ['name' => 'Tonga', 'code' => 'TON', 'code_2' => 'TO', 'phone_code' => '+676', 'currency_code' => 'TOP', 'is_active' => true],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'code_2' => 'TT', 'phone_code' => '+1-868', 'currency_code' => 'TTD', 'is_active' => true],
            ['name' => 'Tunisia', 'code' => 'TUN', 'code_2' => 'TN', 'phone_code' => '+216', 'currency_code' => 'TND', 'is_active' => true],
            ['name' => 'Turkey', 'code' => 'TUR', 'code_2' => 'TR', 'phone_code' => '+90', 'currency_code' => 'TRY', 'is_active' => true],
            ['name' => 'Turkmenistan', 'code' => 'TKM', 'code_2' => 'TM', 'phone_code' => '+993', 'currency_code' => 'TMT', 'is_active' => true],
            ['name' => 'Tuvalu', 'code' => 'TUV', 'code_2' => 'TV', 'phone_code' => '+688', 'currency_code' => 'AUD', 'is_active' => true],
            ['name' => 'Uganda', 'code' => 'UGA', 'code_2' => 'UG', 'phone_code' => '+256', 'currency_code' => 'UGX', 'is_active' => true],
            ['name' => 'Ukraine', 'code' => 'UKR', 'code_2' => 'UA', 'phone_code' => '+380', 'currency_code' => 'UAH', 'is_active' => true],
            ['name' => 'United Arab Emirates', 'code' => 'ARE', 'code_2' => 'AE', 'phone_code' => '+971', 'currency_code' => 'AED', 'is_active' => true],
            ['name' => 'United Kingdom', 'code' => 'GBR', 'code_2' => 'GB', 'phone_code' => '+44', 'currency_code' => 'GBP', 'is_active' => true],
            ['name' => 'United States', 'code' => 'USA', 'code_2' => 'US', 'phone_code' => '+1', 'currency_code' => 'USD', 'is_active' => true],
            ['name' => 'Uruguay', 'code' => 'URY', 'code_2' => 'UY', 'phone_code' => '+598', 'currency_code' => 'UYU', 'is_active' => true],
            ['name' => 'Uzbekistan', 'code' => 'UZB', 'code_2' => 'UZ', 'phone_code' => '+998', 'currency_code' => 'UZS', 'is_active' => true],
            ['name' => 'Vanuatu', 'code' => 'VUT', 'code_2' => 'VU', 'phone_code' => '+678', 'currency_code' => 'VUV', 'is_active' => true],
            ['name' => 'Vatican City', 'code' => 'VAT', 'code_2' => 'VA', 'phone_code' => '+379', 'currency_code' => 'EUR', 'is_active' => true],
            ['name' => 'Venezuela', 'code' => 'VEN', 'code_2' => 'VE', 'phone_code' => '+58', 'currency_code' => 'VES', 'is_active' => true],
            ['name' => 'Vietnam', 'code' => 'VNM', 'code_2' => 'VN', 'phone_code' => '+84', 'currency_code' => 'VND', 'is_active' => true],
            ['name' => 'Yemen', 'code' => 'YEM', 'code_2' => 'YE', 'phone_code' => '+967', 'currency_code' => 'YER', 'is_active' => true],
            ['name' => 'Zambia', 'code' => 'ZMB', 'code_2' => 'ZM', 'phone_code' => '+260', 'currency_code' => 'ZMW', 'is_active' => true],
            ['name' => 'Zimbabwe', 'code' => 'ZWE', 'code_2' => 'ZW', 'phone_code' => '+263', 'currency_code' => 'ZWL', 'is_active' => true],
        ];

        $now = now();

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['code' => $country['code']],
                array_merge($country, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Keep Malawi as it's the primary country for this platform
        DB::table('countries')->whereNotIn('code', ['MWI'])->delete();
    }
};
